services:
  nginx:
    build:
      context: ./food-order-nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: "on-failure"
  db:
    build: 
      context: ./food-order-db/
      dockerfile: Dockerfile.dev
      args:
        - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1533:1433"
    environment: 
      - FOOD_ORDER_PASSWORD=${FOOD_ORDER_PASSWORD}
  frontend:
    build: 
      context: ./food-order-frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./food-order-frontend:/home/node/app
      - /home/node/app/node_modules
  backend:
    build: 
      context: ./food-order-backend/
      dockerfile: Dockerfile.dev
    restart: "on-failure"
    environment: 
      - DB_HOST=db
    ports:
      - "8080:8080"
    volumes:
      - ./food-order-backend:/home/java/app
