FROM openjdk:16-jdk-alpine
RUN mkdir -p /home/java/app
WORKDIR /home/java/app
COPY . .
RUN chmod 774 mvnw
RUN ./mvnw clean install -DskipTests
CMD ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"